<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Application\Product\DeleteProduct\**" />
	  <Compile Remove="Application\Product\GetAllProducts\**" />
	  <Compile Remove="Application\Product\GetProduct\**" />
	  <Compile Remove="Application\Product\UpdateProduct\**" />
	  <Compile Remove="Application\User\CreateUser\**" />
	  <Compile Remove="Application\User\DeleteUser\**" />
	  <Compile Remove="Application\User\GetAllUsers\**" />
	  <Compile Remove="Application\User\GetUser\**" />
	  <Compile Remove="Application\User\UpdateUser\**" />
	  <EmbeddedResource Remove="Application\Product\DeleteProduct\**" />
	  <EmbeddedResource Remove="Application\Product\GetAllProducts\**" />
	  <EmbeddedResource Remove="Application\Product\GetProduct\**" />
	  <EmbeddedResource Remove="Application\Product\UpdateProduct\**" />
	  <EmbeddedResource Remove="Application\User\CreateUser\**" />
	  <EmbeddedResource Remove="Application\User\DeleteUser\**" />
	  <EmbeddedResource Remove="Application\User\GetAllUsers\**" />
	  <EmbeddedResource Remove="Application\User\GetUser\**" />
	  <EmbeddedResource Remove="Application\User\UpdateUser\**" />
	  <None Remove="Application\Product\DeleteProduct\**" />
	  <None Remove="Application\Product\GetAllProducts\**" />
	  <None Remove="Application\Product\GetProduct\**" />
	  <None Remove="Application\Product\UpdateProduct\**" />
	  <None Remove="Application\User\CreateUser\**" />
	  <None Remove="Application\User\DeleteUser\**" />
	  <None Remove="Application\User\GetAllUsers\**" />
	  <None Remove="Application\User\GetUser\**" />
	  <None Remove="Application\User\UpdateUser\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="xunit" Version="2.9.2" />
		<PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.collector" Version="6.0.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="coverlet.msbuild" Version="6.0.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Bogus" Version="35.6.1" />
		<PackageReference Include="FluentAssertions" Version="6.12.0" />
		<PackageReference Include="NSubstitute" Version="5.1.0" />
		<PackageReference Include="Roslynator.Analyzers" Version="4.12.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Roslynator.Testing.CSharp.Xunit" Version="4.12.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Ambev.DeveloperEvaluation.Domain\Ambev.DeveloperEvaluation.Domain.csproj" />
		<ProjectReference Include="..\..\src\Ambev.DeveloperEvaluation.Application\Ambev.DeveloperEvaluation.Application.csproj" />
		<ProjectReference Include="..\..\src\Ambev.DeveloperEvaluation.ORM\Ambev.DeveloperEvaluation.ORM.csproj" />
	</ItemGroup>

</Project>
